
-include $(TOPDIR)/Make.defs
-include $(SDKDIR)/Make.defs

CONFIG_MYAPPS_LUA_PRIORITY ?= SCHED_PRIORITY_DEFAULT
CONFIG_MYAPPS_LUA_STACKSIZE ?= 32768

APPNAME = lua
PRIORITY = $(CONFIG_MYAPPS_LUA_PRIORITY)
STACKSIZE = $(CONFIG_MYAPPS_LUA_STACKSIZE)

ASRCS = setjmp.S
MAINSRC = lua.c
CSRCS = $(filter-out $(MAINSRC), $(wildcard *.c))

CFLAGS += -DSIGINT=SIGUSR1

CONFIG_MYAPPS_LUA_PROGNAME ?= lua$(EXEEXT)
PROGNAME = $(CONFIG_MYAPPS_LUA_PROGNAME)

include $(APPDIR)/Application.mk
